[package]
name = "godot-script"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"
description = "Attachable Rust scripts for the Godot Rust module"
license = "MIT"

[dependencies]
godot = { path = "../../vendor/gdext/godot", features = ["api-custom-json"] }
godot-script-derive = { path = "../godot-script-derive" }
